package com.example.kiwoom.research.boxevaluation.a1;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.kiwoom.research.boxevaluation.repository.A1DatasetRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.r2dbc.core.DatabaseClient;

@SpringBootTest(
        properties = {
            "kiwoom.api.base-url=http://localhost",
            "kiwoom.api.key=test-key",
            "kiwoom.api.secret=test-secret",
            "spring.r2dbc.url=r2dbc:h2:mem:///a1-dataset;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
            "spring.datasource.url=jdbc:h2:mem:a1-dataset-flyway;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
            "spring.datasource.username=sa",
            "spring.sql.init.mode=always",
            "spring.flyway.enabled=false"
        })
class A1DatasetRepositoryTest {
    @Autowired private A1DatasetRepository repository;
    @Autowired private DatabaseClient database;

    @Test
    void existingDatasetIsReturnedWithoutResamplingOrMutation() {
        database.sql(
                        """
                        CREATE TABLE box_research_dataset (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            dataset_key VARCHAR(80) NOT NULL UNIQUE,
                            dataset_type VARCHAR(20) NOT NULL,
                            source_batch_id BIGINT,
                            sampling_policy_json TEXT NOT NULL,
                            blind_policy_version VARCHAR(50) NOT NULL,
                            feature_snapshot_version VARCHAR(50) NOT NULL,
                            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)
                        """)
                .fetch()
                .rowsUpdated()
                .onErrorResume(error -> reactor.core.publisher.Mono.just(0L))
                .block();
        String key = "A1-TEST-" + System.nanoTime();
        var first = repository.createOrGet(key, "manifest-one", "blind-v1", "features-v1").block();
        var second = repository.createOrGet(key, "manifest-two", "blind-v2", "features-v2").block();
        assertThat(first).isNotNull();
        assertThat(second.id()).isEqualTo(first.id());
        assertThat(second.samplingPolicyJson()).isEqualTo("manifest-one");
        assertThat(second.blindPolicyVersion()).isEqualTo("blind-v1");
        assertThat(second.featureSnapshotVersion()).isEqualTo("features-v1");
    }
}
