package com.example.kiwoom.research.boxevaluation.a1;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.LocalDate;
import java.util.stream.IntStream;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInfo;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.r2dbc.core.DatabaseClient;

@SpringBootTest(
        properties = {
            "spring.r2dbc.url=r2dbc:h2:mem:///a1-generation;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
            "spring.datasource.url=jdbc:h2:mem:a1-generation;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
            "spring.datasource.username=sa",
            "spring.sql.init.mode=always",
            "spring.flyway.enabled=false"
        })
class A1GenerationServiceTest {
    @Autowired private A1GenerationService generation;
    @Autowired private A1BlindRepository blindRepository;

    @Autowired
    private com.example.kiwoom.research.boxevaluation.repository.BoxEvaluationRepository
            evaluationRepository;

    @Autowired private DatabaseClient database;
    @Autowired private ObjectMapper objectMapper;

    @BeforeEach
    void schema(TestInfo testInfo) {
        database.sql("DROP ALL OBJECTS").fetch().rowsUpdated().block();
        database.sql(
                        "CREATE TABLE stock_master (code VARCHAR(6) PRIMARY KEY, name VARCHAR(100), market VARCHAR(20), product_type VARCHAR(30), active BOOLEAN)")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "CREATE TABLE historical_backfill_state (code VARCHAR(6) PRIMARY KEY, status VARCHAR(40))")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "CREATE TABLE daily_candle (code VARCHAR(6), trade_date DATE, open_price BIGINT, high_price BIGINT, low_price BIGINT, close_price BIGINT, volume BIGINT, PRIMARY KEY(code, trade_date))")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "CREATE TABLE strategy_definition (id BIGINT PRIMARY KEY, strategy_id VARCHAR(80), version INT, name VARCHAR(120), description VARCHAR(1000), status VARCHAR(30), parameters_json VARCHAR(4000), created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "CREATE TABLE box_research_dataset (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dataset_key VARCHAR(100) UNIQUE NOT NULL, dataset_type VARCHAR(20) NOT NULL, source_batch_id BIGINT, sampling_policy_json TEXT, blind_policy_version VARCHAR(100), feature_snapshot_version VARCHAR(100), created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "CREATE TABLE box_evaluation_batch (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, strategy_version_id BIGINT, name VARCHAR(150), dataset_version VARCHAR(100), candidate_generator_version VARCHAR(100), sampling_policy_json VARCHAR(4000), blind_policy_version VARCHAR(50), status VARCHAR(20), created_by VARCHAR(100), created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "CREATE TABLE box_evaluation_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id BIGINT, code VARCHAR(6), cutoff_date DATE, display_order INT, source_scan_id BIGINT, data_hash VARCHAR(128), status VARCHAR(20), lock_version BIGINT DEFAULT 0, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)")
                .fetch()
                .rowsUpdated()
                .block();
        String candidateConstraint =
                testInfo.getTestMethod()
                                .map(method -> method.getName().contains("rollsBack"))
                                .orElse(false)
                        ? ", CHECK (1=0)"
                        : "";
        database.sql(
                        "CREATE TABLE box_evaluation_candidate (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, item_id BIGINT, candidate_key VARCHAR(30), start_date DATE, end_date DATE, rank_no INT, feature_json VARCHAR(4000), generator_version VARCHAR(100), created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP"
                                + candidateConstraint
                                + ")")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "INSERT INTO strategy_definition(id,strategy_id,version,name,description,status,parameters_json) VALUES (1,'a1',1,'A1','fixture','PAPER_ENABLED','{}')")
                .fetch()
                .rowsUpdated()
                .block();
        IntStream.range(0, 20)
                .forEach(
                        index -> {
                            String market = index < 10 ? "KOSPI" : "KOSDAQ";
                            String code = String.format("%06d", 910000 + index);
                            database.sql(
                                            "INSERT INTO stock_master(code,name,market,product_type,active) VALUES (:code,:name,:market,'STOCK',TRUE)")
                                    .bind("code", code)
                                    .bind("name", "fixture")
                                    .bind("market", market)
                                    .fetch()
                                    .rowsUpdated()
                                    .block();
                            database.sql(
                                            "INSERT INTO historical_backfill_state(code,status) VALUES (:code,'TARGET_REACHED')")
                                    .bind("code", code)
                                    .fetch()
                                    .rowsUpdated()
                                    .block();
                            IntStream.range(0, 252)
                                    .forEach(
                                            day ->
                                                    database.sql(
                                                                    "INSERT INTO daily_candle(code,trade_date,open_price,high_price,low_price,close_price,volume) VALUES (:code,:date,100,110,90,105,1000)")
                                                            .bind("code", code)
                                                            .bind(
                                                                    "date",
                                                                    LocalDate.of(2015, 1, 1)
                                                                            .plusDays(day))
                                                            .fetch()
                                                            .rowsUpdated()
                                                            .block());
                        });
    }

    @Test
    void createsCompleteA1UnitAndSecondCallIsIdempotent() {
        var first = generation.generateA1().block();
        assertThat(first).isNotNull();
        assertThat(first.samples()).hasSize(20);
        assertThat(first.dataset().sourceBatchId()).isEqualTo(first.batch().id());
        assertThat(count("box_research_dataset")).isEqualTo(1);
        assertThat(count("box_evaluation_batch")).isEqualTo(1);
        assertThat(count("box_evaluation_item")).isEqualTo(20);
        assertThat(count("box_evaluation_candidate")).isGreaterThan(0);
        assertThat(count("box_evaluation_item", "status='PENDING'")).isEqualTo(20);

        var second = generation.generateA1().block();
        assertThat(second.dataset().id()).isEqualTo(first.dataset().id());
        assertThat(second.batch().id()).isEqualTo(first.batch().id());
        assertThat(second.samples()).isEqualTo(first.samples());
        assertThat(count("box_research_dataset")).isEqualTo(1);
        assertThat(count("box_evaluation_batch")).isEqualTo(1);
        assertThat(count("box_evaluation_item")).isEqualTo(20);
    }

    @Test
    void rejectsIncompleteExistingDatasetWithoutRepairingIt() {
        database.sql(
                        "INSERT INTO box_research_dataset(dataset_key,dataset_type,sampling_policy_json,blind_policy_version,feature_snapshot_version) VALUES ('BOX-FORMATION-DISCOVERY-A1','DISCOVERY','{}','a1-blind-v1','none-a1')")
                .fetch()
                .rowsUpdated()
                .block();

        assertThatThrownBy(() -> generation.generateA1().block())
                .isInstanceOf(A1SamplingException.class)
                .hasMessageContaining("INCOMPLETE_EXISTING_DATASET");
        assertThat(count("box_research_dataset")).isEqualTo(1);
        assertThat(count("box_evaluation_batch")).isZero();
        assertThat(count("box_evaluation_item")).isZero();
    }

    @Test
    void rejectsConflictingExistingDatasetWithoutRepairingIt() {
        database.sql(
                        "INSERT INTO box_research_dataset(dataset_key,dataset_type,sampling_policy_json,blind_policy_version,feature_snapshot_version) VALUES ('BOX-FORMATION-DISCOVERY-A1','OTHER','{}','a1-blind-v1','none-a1')")
                .fetch()
                .rowsUpdated()
                .block();

        assertThatThrownBy(() -> generation.generateA1().block())
                .isInstanceOf(A1SamplingException.class)
                .hasMessageContaining("conflicting A1 dataset type");
        assertThat(count("box_research_dataset")).isEqualTo(1);
        assertThat(count("box_evaluation_batch")).isZero();
    }

    @Test
    void rejectsGenerationWhenNoStrategyDefinitionExists() {
        database.sql("DELETE FROM strategy_definition").fetch().rowsUpdated().block();

        assertThatThrownBy(() -> generation.generateA1().block())
                .isInstanceOf(A1SamplingException.class)
                .hasMessageContaining("no strategy definition exists");
        assertThat(count("box_research_dataset")).isZero();
        assertThat(count("box_evaluation_batch")).isZero();
    }

    @Test
    void blindPayloadUsesOnlyCutoffCandles() {
        var result = generation.generateA1().block();
        var item = evaluationRepository.findItems(result.batch().id()).next().block();
        var payload = blindRepository.findPayload(item.id()).block();

        assertThat(payload).isNotNull();
        assertThat(payload.candles()).isNotEmpty();
        assertThat(payload.candles())
                .allMatch(candle -> !candle.tradeDate().isAfter(payload.cutoffDate()));
    }

    @Test
    void persistsHistoricalEligibilityEvidenceDuringGeneration() throws Exception {
        var result = generation.generateA1().block();
        String manifest = datasetManifest();
        var parsed = objectMapper.readTree(manifest);
        assertThat(parsed.get("samples")).hasSize(20);
        assertThat(parsed.at("/samples/0/historicalBackfillStatus").asText())
                .isEqualTo("TARGET_REACHED");
        assertThat(parsed.at("/samples/0/minimumContextCandles").asInt()).isEqualTo(252);
        assertThat(parsed.at("/samples/0/actualContextCandleCount").asInt())
                .isGreaterThanOrEqualTo(252);
        assertThat(parsed.at("/samples/0/cutoffIsActualTradingDate").asBoolean()).isTrue();
        assertThat(result.samples())
                .allSatisfy(
                        sample ->
                                assertThat(sample.historicalBackfillStatus())
                                        .isEqualTo("TARGET_REACHED"));
    }

    @Test
    void correctsLegacyEvidenceWithoutChangingA1IdentityAndIsIdempotent() throws Exception {
        var first = generation.generateA1().block();
        var legacySamples =
                first.samples().stream()
                        .map(
                                sample ->
                                        new A1Sample(
                                                sample.code(),
                                                sample.market(),
                                                sample.cutoffDate(),
                                                sample.assignedStratum(),
                                                sample.actualStratum(),
                                                sample.fallbackApplied()))
                        .toList();
        replaceManifest(
                new A1DatasetManifest(
                        A1DatasetService.DATASET_KEY,
                        A1DatasetService.DATASET_TYPE,
                        A1DatasetService.STAGE,
                        A1Sampler.SEED,
                        A1Sampler.ALGORITHM_VERSION,
                        legacySamples));

        var corrected = generation.correctExistingA1EligibilityEvidence().block();
        String correctedManifest = datasetManifest();
        var repeated = generation.correctExistingA1EligibilityEvidence().block();

        assertThat(corrected.dataset().id()).isEqualTo(first.dataset().id());
        assertThat(corrected.batch().id()).isEqualTo(first.batch().id());
        assertThat(repeated.dataset().id()).isEqualTo(first.dataset().id());
        assertThat(datasetManifest()).isEqualTo(correctedManifest);
        assertThat(
                        objectMapper
                                .readTree(correctedManifest)
                                .at("/samples/0/historicalBackfillStatus")
                                .asText())
                .isEqualTo("TARGET_REACHED");
        assertThat(count("box_research_dataset")).isEqualTo(1);
        assertThat(count("box_evaluation_batch")).isEqualTo(1);
        assertThat(count("box_evaluation_item")).isEqualTo(20);
    }

    @Test
    void rejectsConflictingPersistedEligibilityEvidenceWithoutOverwriting() throws Exception {
        var first = generation.generateA1().block();
        var samples = new java.util.ArrayList<>(first.samples());
        var original = samples.get(0);
        samples.set(
                0,
                new A1Sample(
                        original.code(),
                        original.market(),
                        original.cutoffDate(),
                        original.assignedStratum(),
                        original.actualStratum(),
                        original.fallbackApplied(),
                        "TARGET_REACHED",
                        252,
                        251,
                        true));
        replaceManifest(
                new A1DatasetManifest(
                        A1DatasetService.DATASET_KEY,
                        A1DatasetService.DATASET_TYPE,
                        A1DatasetService.STAGE,
                        A1Sampler.SEED,
                        A1Sampler.ALGORITHM_VERSION,
                        samples));
        String before = datasetManifest();

        assertThatThrownBy(() -> generation.correctExistingA1EligibilityEvidence().block())
                .isInstanceOf(A1SamplingException.class)
                .hasMessageContaining("conflicting eligibility evidence");
        assertThat(datasetManifest()).isEqualTo(before);
        assertThat(first.dataset().id())
                .isEqualTo(
                        database.sql(
                                        "SELECT id FROM box_research_dataset WHERE dataset_key='BOX-FORMATION-DISCOVERY-A1'")
                                .map((row, metadata) -> ((Number) row.get("id")).longValue())
                                .one()
                                .block());
    }

    @Test
    void rejectsSourceEligibilityMismatchWithoutMutation() throws Exception {
        var first = generation.generateA1().block();
        var legacySamples =
                first.samples().stream()
                        .map(
                                sample ->
                                        new A1Sample(
                                                sample.code(),
                                                sample.market(),
                                                sample.cutoffDate(),
                                                sample.assignedStratum(),
                                                sample.actualStratum(),
                                                sample.fallbackApplied()))
                        .toList();
        replaceManifest(
                new A1DatasetManifest(
                        A1DatasetService.DATASET_KEY,
                        A1DatasetService.DATASET_TYPE,
                        A1DatasetService.STAGE,
                        A1Sampler.SEED,
                        A1Sampler.ALGORITHM_VERSION,
                        legacySamples));
        String before = datasetManifest();
        database.sql("UPDATE historical_backfill_state SET status='HISTORY_EXHAUSTED'")
                .fetch()
                .rowsUpdated()
                .block();

        assertThatThrownBy(() -> generation.correctExistingA1EligibilityEvidence().block())
                .isInstanceOf(A1SamplingException.class)
                .hasMessageContaining("not currently eligible");
        assertThat(datasetManifest()).isEqualTo(before);
    }

    @Test
    void rollsBackDatasetAndBatchWhenCandidatePersistenceFails() {
        assertThatThrownBy(() -> generation.generateA1().block())
                .isInstanceOf(RuntimeException.class);
        assertThat(count("box_research_dataset")).isZero();
        assertThat(count("box_evaluation_batch")).isZero();
        assertThat(count("box_evaluation_item")).isZero();
    }

    private long count(String table) {
        return count(table, "TRUE");
    }

    private long count(String table, String condition) {
        return database.sql("SELECT COUNT(*) AS n FROM " + table + " WHERE " + condition)
                .map((row, metadata) -> ((Number) row.get("n")).longValue())
                .one()
                .block();
    }

    private String datasetManifest() {
        return database.sql(
                        "SELECT sampling_policy_json FROM box_research_dataset WHERE dataset_key='BOX-FORMATION-DISCOVERY-A1'")
                .map((row, metadata) -> row.get("sampling_policy_json", String.class))
                .one()
                .block();
    }

    private void replaceManifest(A1DatasetManifest manifest) throws Exception {
        database.sql(
                        "UPDATE box_research_dataset SET sampling_policy_json=:manifest WHERE dataset_key='BOX-FORMATION-DISCOVERY-A1'")
                .bind("manifest", objectMapper.writeValueAsString(manifest))
                .fetch()
                .rowsUpdated()
                .block();
    }
}
