package com.example.kiwoom.research.boxevaluation;

import static org.assertj.core.api.Assertions.assertThat;

import com.example.kiwoom.research.boxevaluation.model.BoxResearchDataset;
import com.example.kiwoom.research.boxevaluation.repository.BoxEvaluationRepository;
import com.example.kiwoom.research.boxevaluation.sampling.StratifiedDiscoverySampler;
import java.time.LocalDate;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.r2dbc.core.DatabaseClient;

/**
 * Persistence-backed smoke test for the Discovery entry point and deterministic selection contract.
 */
@SpringBootTest(
        properties = {
            "spring.r2dbc.url=r2dbc:h2:mem:///discovery-pipeline;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
            "spring.datasource.url=jdbc:h2:mem:discovery-pipeline;MODE=PostgreSQL;DB_CLOSE_DELAY=-1",
            "spring.datasource.username=sa",
            "spring.sql.init.mode=always",
            "spring.flyway.enabled=false"
        })
class DiscoveryPipelineIntegrationTest {
    @Autowired BoxEvaluationRepository repository;
    @Autowired DatabaseClient database;

    @org.junit.jupiter.api.BeforeEach
    void schema() {
        database.sql(
                        "CREATE TABLE IF NOT EXISTS box_research_dataset (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, dataset_key VARCHAR(100) UNIQUE NOT NULL, dataset_type VARCHAR(20) NOT NULL, source_batch_id BIGINT, sampling_policy_json VARCHAR(4000), blind_policy_version VARCHAR(100), feature_snapshot_version VARCHAR(100), created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "CREATE TABLE IF NOT EXISTS strategy_definition (id BIGINT PRIMARY KEY, strategy_id VARCHAR(80), version INT, name VARCHAR(120), description VARCHAR(1000), status VARCHAR(30), parameters_json VARCHAR(4000))")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "INSERT INTO strategy_definition(id,strategy_id,version,name,description,status,parameters_json) VALUES (1,'discovery-test',1,'Discovery','fixture','PAPER_ENABLED','{}')")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "CREATE TABLE IF NOT EXISTS stock_master (code VARCHAR(6) PRIMARY KEY, name VARCHAR(100), market VARCHAR(20))")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "INSERT INTO stock_master(code,name,market,product_type,active) VALUES ('100001','Discovery 1','KOSPI','STOCK',TRUE),('100002','Discovery 2','KOSDAQ','STOCK',TRUE)")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "CREATE TABLE IF NOT EXISTS box_evaluation_batch (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, strategy_version_id BIGINT, name VARCHAR(150), dataset_version VARCHAR(100), candidate_generator_version VARCHAR(100), sampling_policy_json VARCHAR(4000), blind_policy_version VARCHAR(50), status VARCHAR(20), created_by VARCHAR(100), created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)")
                .fetch()
                .rowsUpdated()
                .block();
        database.sql(
                        "CREATE TABLE IF NOT EXISTS box_evaluation_item (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id BIGINT, code VARCHAR(6), cutoff_date DATE, display_order INT, source_scan_id BIGINT, data_hash VARCHAR(128), status VARCHAR(20), lock_version BIGINT DEFAULT 0, created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP)")
                .fetch()
                .rowsUpdated()
                .block();
    }

    @Test
    void discoveryDatasetPersistsAndSamplerSelectionIsDeterministic() {
        var dataset =
                new BoxResearchDataset(
                        null,
                        "DISCOVERY-TEST",
                        "DISCOVERY",
                        null,
                        "{\"durationBuckets\":[15],\"widthBuckets\":[5],\"seed\":11}",
                        "BLIND-V1",
                        "FEATURE-V1",
                        null);
        assertThat(repository.createDataset(dataset).block()).isNotNull();
        var candidates =
                List.of(
                        new StratifiedDiscoverySampler.Candidate(
                                "DISC-A", java.time.LocalDate.of(2024, 1, 1), 10, 2, "BULL"),
                        new StratifiedDiscoverySampler.Candidate(
                                "DISC-B", java.time.LocalDate.of(2024, 2, 1), 30, 8, "BEAR"));
        var config = new StratifiedDiscoverySampler.Configuration(List.of(15), List.of(5), 2, 11);
        var sampler = new StratifiedDiscoverySampler();
        assertThat(sampler.sample(candidates, config))
                .containsExactlyElementsOf(sampler.sample(candidates, config));
        assertThat(
                        repository
                                .findDatasets()
                                .filter(d -> d.datasetKey().equals("DISCOVERY-TEST"))
                                .next()
                                .block()
                                .datasetType())
                .isEqualTo("DISCOVERY");
        var batch =
                repository
                        .createBatch(
                                new com.example.kiwoom.research.boxevaluation.model
                                        .BoxEvaluationBatch(
                                        null,
                                        1,
                                        "DISCOVERY-TEST-BATCH",
                                        "DISCOVERY-TEST",
                                        "SAMPLER-1",
                                        "{\"seed\":11}",
                                        "BLIND-V1",
                                        com.example.kiwoom.research.boxevaluation.model
                                                .BoxEvaluationBatchStatus.READY,
                                        "test",
                                        null))
                        .block();
        assertThat(batch).isNotNull();
        var first =
                repository
                        .createItem(
                                new com.example.kiwoom.research.boxevaluation.model
                                        .BoxEvaluationItem(
                                        null,
                                        batch.id(),
                                        "100001",
                                        LocalDate.of(2024, 1, 1),
                                        1,
                                        null,
                                        "hash-disc01",
                                        com.example.kiwoom.research.boxevaluation.model
                                                .BoxEvaluationItemStatus.PENDING,
                                        0,
                                        null))
                        .block();
        var second =
                repository
                        .createItem(
                                new com.example.kiwoom.research.boxevaluation.model
                                        .BoxEvaluationItem(
                                        null,
                                        batch.id(),
                                        "100002",
                                        LocalDate.of(2024, 2, 1),
                                        2,
                                        null,
                                        "hash-disc02",
                                        com.example.kiwoom.research.boxevaluation.model
                                                .BoxEvaluationItemStatus.PENDING,
                                        0,
                                        null))
                        .block();
        assertThat(repository.progress(batch.id()).block())
                .extracting("completed", "total")
                .containsExactly(0L, 2L);
        assertThat(repository.findNext(batch.id()).block().id()).isEqualTo(first.id());
        database.sql("UPDATE box_evaluation_item SET status='COMMITTED' WHERE id=:id")
                .bind("id", first.id())
                .fetch()
                .rowsUpdated()
                .block();
        assertThat(repository.progress(batch.id()).block())
                .extracting("completed", "total")
                .containsExactly(1L, 2L);
        assertThat(repository.findNext(batch.id()).block().id()).isEqualTo(second.id());
        database.sql("UPDATE box_evaluation_item SET status='COMMITTED' WHERE id=:id")
                .bind("id", second.id())
                .fetch()
                .rowsUpdated()
                .block();
        assertThat(repository.progress(batch.id()).block())
                .extracting("completed", "total")
                .containsExactly(2L, 2L);
        assertThat(repository.findNext(batch.id()).block()).isNull();
    }
}
