CREATE TABLE IF NOT EXISTS watchlist (
    code VARCHAR(6) PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio_position (
    code VARCHAR(6) PRIMARY KEY,
    quantity NUMERIC(20, 4) NOT NULL CHECK (quantity > 0),
    average_price NUMERIC(20, 4) NOT NULL CHECK (average_price > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
