CREATE TABLE IF NOT EXISTS watchlist (
    username VARCHAR(100) NOT NULL,
    code VARCHAR(6) NOT NULL,
    group_name VARCHAR(50) NOT NULL DEFAULT '기본',
    note VARCHAR(500) NOT NULL DEFAULT '',
    PRIMARY KEY (username, code),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS portfolio_position (
    username VARCHAR(100) NOT NULL,
    code VARCHAR(6) NOT NULL,
    quantity NUMERIC(20, 4) NOT NULL CHECK (quantity > 0),
    average_price NUMERIC(20, 4) NOT NULL CHECK (average_price > 0),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (username, code)
);

CREATE TABLE IF NOT EXISTS portfolio_trade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    code VARCHAR(6) NOT NULL,
    trade_type VARCHAR(4) NOT NULL CHECK (trade_type IN ('BUY', 'SELL')),
    quantity NUMERIC(20, 4) NOT NULL CHECK (quantity > 0),
    price NUMERIC(20, 4) NOT NULL CHECK (price > 0),
    fee NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (fee >= 0),
    tax NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (tax >= 0),
    realized_profit_loss NUMERIC(20, 4) NOT NULL DEFAULT 0,
    traded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert_rule (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    code VARCHAR(6) NOT NULL,
    condition_type VARCHAR(20) NOT NULL CHECK (condition_type IN ('PRICE_ABOVE', 'PRICE_BELOW', 'CHANGE_RATE_ABOVE', 'CHANGE_RATE_BELOW', 'RSI_ABOVE', 'RSI_BELOW', 'MACD_CROSS_UP', 'MACD_CROSS_DOWN')),
    threshold NUMERIC(20, 4),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_state BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (username, code, condition_type, threshold)
);

CREATE TABLE IF NOT EXISTS alert_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id BIGINT REFERENCES alert_rule(id) ON DELETE SET NULL,
    username VARCHAR(100) NOT NULL,
    code VARCHAR(6) NOT NULL,
    condition_type VARCHAR(20) NOT NULL,
    observed_value NUMERIC(20, 4) NOT NULL,
    threshold NUMERIC(20, 4),
    triggered_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE IF NOT EXISTS stock_master (
    code VARCHAR(6) PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    market VARCHAR(20) NOT NULL,
    product_type VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS stock_master_snapshot (
    snapshot_date DATE NOT NULL,
    code VARCHAR(6) NOT NULL,
    name VARCHAR(200) NOT NULL,
    market VARCHAR(20) NOT NULL,
    product_type VARCHAR(30) NOT NULL,
    captured_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (snapshot_date, code)
);

CREATE TABLE IF NOT EXISTS daily_candle (
    code VARCHAR(6) NOT NULL REFERENCES stock_master(code),
    trade_date DATE NOT NULL,
    open_price BIGINT NOT NULL,
    high_price BIGINT NOT NULL,
    low_price BIGINT NOT NULL,
    close_price BIGINT NOT NULL,
    volume BIGINT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (code, trade_date)
);

CREATE TABLE IF NOT EXISTS market_data_sync_state (
    code VARCHAR(6) PRIMARY KEY REFERENCES stock_master(code),
    last_synced_date DATE,
    status VARCHAR(20) NOT NULL,
    error_message VARCHAR(500),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS strategy_scan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_version VARCHAR(100) NOT NULL,
    box_range_days INTEGER NOT NULL,
    scanned_count INTEGER NOT NULL,
    scope VARCHAR(500) NOT NULL,
    data_as_of DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS strategy_candidate_snapshot (
    scan_id BIGINT NOT NULL REFERENCES strategy_scan(id) ON DELETE CASCADE,
    rank_no INTEGER NOT NULL,
    code VARCHAR(6) NOT NULL,
    name VARCHAR(200) NOT NULL,
    current_price BIGINT NOT NULL,
    score INTEGER NOT NULL,
    qualified BOOLEAN NOT NULL,
    drawdown_rate DOUBLE PRECISION NOT NULL,
    box_range_rate DOUBLE PRECISION NOT NULL,
    volume_spike_count INTEGER NOT NULL,
    breakout_rate DOUBLE PRECISION NOT NULL,
    pullback_rate DOUBLE PRECISION NOT NULL,
    matched_conditions TEXT NOT NULL,
    PRIMARY KEY (scan_id, code)
);

CREATE TABLE IF NOT EXISTS market_data_quality_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_version VARCHAR(100) NOT NULL,
    stock_count INTEGER NOT NULL,
    candle_count BIGINT NOT NULL,
    blocking_issue_count INTEGER NOT NULL,
    warning_issue_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS market_data_quality_issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES market_data_quality_run(id) ON DELETE CASCADE,
    code VARCHAR(6) NOT NULL,
    trade_date DATE,
    issue_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    detail VARCHAR(500) NOT NULL
);

CREATE TABLE IF NOT EXISTS backtest_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_version VARCHAR(100) NOT NULL,
    code VARCHAR(6) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    initial_capital NUMERIC(20, 4) NOT NULL,
    final_capital NUMERIC(20, 4) NOT NULL,
    fee_rate DOUBLE PRECISION NOT NULL,
    tax_rate DOUBLE PRECISION NOT NULL,
    slippage_rate DOUBLE PRECISION NOT NULL,
    trade_count INTEGER NOT NULL,
    win_rate DOUBLE PRECISION NOT NULL,
    total_return_rate DOUBLE PRECISION NOT NULL,
    max_drawdown_rate DOUBLE PRECISION NOT NULL,
    expectancy NUMERIC(20, 4) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS backtest_trade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES backtest_run(id) ON DELETE CASCADE,
    entry_date DATE NOT NULL,
    exit_date DATE NOT NULL,
    entry_price NUMERIC(20, 4) NOT NULL,
    exit_price NUMERIC(20, 4) NOT NULL,
    quantity BIGINT NOT NULL,
    gross_profit_loss NUMERIC(20, 4) NOT NULL,
    fee NUMERIC(20, 4) NOT NULL,
    tax NUMERIC(20, 4) NOT NULL,
    slippage_cost NUMERIC(20, 4) NOT NULL,
    net_profit_loss NUMERIC(20, 4) NOT NULL,
    return_rate DOUBLE PRECISION NOT NULL,
    exit_reason VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS walk_forward_report (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_version VARCHAR(100) NOT NULL,
    code VARCHAR(6) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    training_days INTEGER NOT NULL,
    validation_days INTEGER NOT NULL,
    step_days INTEGER NOT NULL,
    fold_count INTEGER NOT NULL,
    validation_trade_count INTEGER NOT NULL,
    cost_adjusted_expectancy NUMERIC(20, 4) NOT NULL,
    max_drawdown_rate DOUBLE PRECISION NOT NULL,
    average_return_rate DOUBLE PRECISION NOT NULL,
    cost_drag NUMERIC(20, 4) NOT NULL,
    passed BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS walk_forward_fold (
    report_id BIGINT NOT NULL REFERENCES walk_forward_report(id) ON DELETE CASCADE,
    fold_no INTEGER NOT NULL,
    training_start DATE NOT NULL,
    training_end DATE NOT NULL,
    validation_start DATE NOT NULL,
    validation_end DATE NOT NULL,
    training_trade_count INTEGER NOT NULL,
    training_return_rate DOUBLE PRECISION NOT NULL,
    validation_trade_count INTEGER NOT NULL,
    validation_win_rate DOUBLE PRECISION NOT NULL,
    validation_expectancy NUMERIC(20, 4) NOT NULL,
    validation_return_rate DOUBLE PRECISION NOT NULL,
    validation_max_drawdown_rate DOUBLE PRECISION NOT NULL,
    cost_drag NUMERIC(20, 4) NOT NULL,
    PRIMARY KEY (report_id, fold_no)
);

CREATE TABLE IF NOT EXISTS trading_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    decision_id VARCHAR(100) NOT NULL UNIQUE,
    mode VARCHAR(20) NOT NULL,
    code VARCHAR(6) NOT NULL,
    side VARCHAR(10) NOT NULL,
    requested_quantity BIGINT NOT NULL CHECK (requested_quantity > 0),
    requested_price NUMERIC(20, 4) NOT NULL CHECK (requested_price > 0),
    status VARCHAR(30) NOT NULL,
    filled_quantity BIGINT NOT NULL DEFAULT 0,
    average_fill_price NUMERIC(20, 4),
    rejection_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trading_order_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES trading_order(id) ON DELETE CASCADE,
    from_status VARCHAR(30),
    to_status VARCHAR(30) NOT NULL,
    detail VARCHAR(500) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS trading_fill (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    execution_id VARCHAR(100) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL REFERENCES trading_order(id) ON DELETE CASCADE,
    code VARCHAR(6) NOT NULL,
    side VARCHAR(10) NOT NULL,
    quantity BIGINT NOT NULL CHECK (quantity > 0),
    price NUMERIC(20, 4) NOT NULL CHECK (price > 0),
    fee NUMERIC(20, 4) NOT NULL DEFAULT 0,
    tax NUMERIC(20, 4) NOT NULL DEFAULT 0,
    filled_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS paper_account (
    id INTEGER PRIMARY KEY CHECK (id = 1),
    initial_cash NUMERIC(20, 4) NOT NULL,
    cash NUMERIC(20, 4) NOT NULL,
    peak_equity NUMERIC(20, 4) NOT NULL,
    trading_day DATE NOT NULL,
    day_start_equity NUMERIC(20, 4) NOT NULL,
    kill_switch_active BOOLEAN NOT NULL DEFAULT FALSE,
    kill_switch_reason VARCHAR(500),
    kill_switch_activated_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS paper_position (
    code VARCHAR(6) PRIMARY KEY,
    quantity BIGINT NOT NULL CHECK (quantity > 0),
    average_price NUMERIC(20, 4) NOT NULL CHECK (average_price > 0),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
