CREATE TABLE market_data_quality_run (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_version VARCHAR(100) NOT NULL,
    stock_count INTEGER NOT NULL,
    candle_count BIGINT NOT NULL,
    blocking_issue_count INTEGER NOT NULL,
    warning_issue_count INTEGER NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE market_data_quality_issue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL REFERENCES market_data_quality_run(id) ON DELETE CASCADE,
    code VARCHAR(6) NOT NULL,
    trade_date DATE,
    issue_type VARCHAR(50) NOT NULL,
    severity VARCHAR(20) NOT NULL,
    detail VARCHAR(500) NOT NULL
);

CREATE INDEX idx_market_data_quality_run_created ON market_data_quality_run(created_at DESC);
CREATE INDEX idx_market_data_quality_blocking ON market_data_quality_issue(run_id, code, severity);
