CREATE TABLE portfolio_trade (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(6) NOT NULL,
    trade_type VARCHAR(4) NOT NULL CHECK (trade_type IN ('BUY', 'SELL')),
    quantity NUMERIC(20, 4) NOT NULL CHECK (quantity > 0),
    price NUMERIC(20, 4) NOT NULL CHECK (price > 0),
    fee NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (fee >= 0),
    tax NUMERIC(20, 4) NOT NULL DEFAULT 0 CHECK (tax >= 0),
    realized_profit_loss NUMERIC(20, 4) NOT NULL DEFAULT 0,
    traded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT portfolio_trade_code_format CHECK (code ~ '^[0-9]{6}$')
);

CREATE INDEX idx_portfolio_trade_code_traded_at ON portfolio_trade(code, traded_at DESC);
