CREATE TABLE historical_backfill_state (
    code VARCHAR(6) PRIMARY KEY REFERENCES stock_master(code),
    target_start_date DATE NOT NULL,
    oldest_synced_date DATE,
    status VARCHAR(32) NOT NULL,
    exhaustion_reason VARCHAR(40),
    continuation_key VARCHAR(500),
    continuation_active BOOLEAN NOT NULL DEFAULT FALSE,
    page_count INTEGER NOT NULL DEFAULT 0,
    candle_count BIGINT NOT NULL DEFAULT 0,
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error_code VARCHAR(100),
    last_error_message VARCHAR(500),
    started_at TIMESTAMP WITH TIME ZONE,
    last_checkpoint_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_historical_backfill_status
    ON historical_backfill_state(status, updated_at);

CREATE TABLE historical_backfill_run (
    run_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    target_start_date DATE NOT NULL,
    target_end_date DATE NOT NULL,
    universe_policy VARCHAR(64) NOT NULL,
    universe_snapshot_date DATE,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP WITH TIME ZONE,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
