CREATE TABLE strategy_scan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    strategy_version VARCHAR(100) NOT NULL,
    box_range_days INTEGER NOT NULL,
    scanned_count INTEGER NOT NULL,
    scope VARCHAR(500) NOT NULL,
    data_as_of DATE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE strategy_candidate_snapshot (
    scan_id BIGINT NOT NULL REFERENCES strategy_scan(id) ON DELETE CASCADE,
    rank_no INTEGER NOT NULL,
    code VARCHAR(6) NOT NULL,
    name VARCHAR(200) NOT NULL,
    current_price BIGINT NOT NULL,
    score INTEGER NOT NULL,
    qualified BOOLEAN NOT NULL,
    drawdown_rate DOUBLE PRECISION NOT NULL,
    box_range_rate DOUBLE PRECISION NOT NULL,
    volume_spike_count INTEGER NOT NULL,
    breakout_rate DOUBLE PRECISION NOT NULL,
    pullback_rate DOUBLE PRECISION NOT NULL,
    matched_conditions TEXT NOT NULL,
    PRIMARY KEY (scan_id, code)
);

CREATE INDEX idx_strategy_scan_created_at ON strategy_scan(created_at DESC);
CREATE INDEX idx_strategy_candidate_qualified ON strategy_candidate_snapshot(scan_id, qualified, score DESC);
